// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv7Xg7KLt2keTBm6Kb0S0Uyultl6YmmE0',
    appId: '1:302397930802:web:fdf80fac60590b60336b2b',
    messagingSenderId: '302397930802',
    projectId: 'flutter-lovers-323ec',
    authDomain: 'flutter-lovers-323ec.firebaseapp.com',
    storageBucket: 'flutter-lovers-323ec.appspot.com',
    measurementId: 'G-0BMM9YRVX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Du2_3FTD31MrAXe8FqLipz7DhGYRm1k',
    appId: '1:302397930802:android:cebea07da1745e7f336b2b',
    messagingSenderId: '302397930802',
    projectId: 'flutter-lovers-323ec',
    storageBucket: 'flutter-lovers-323ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKt9QIcosxJBLxATH6wNqbq3ZSs5Pnolg',
    appId: '1:302397930802:ios:70ce588b3f1298a1336b2b',
    messagingSenderId: '302397930802',
    projectId: 'flutter-lovers-323ec',
    storageBucket: 'flutter-lovers-323ec.appspot.com',
    iosClientId: '302397930802-l4vr062indvb6la02vk5s1m8gt1h0cca.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCanliSohbetUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKt9QIcosxJBLxATH6wNqbq3ZSs5Pnolg',
    appId: '1:302397930802:ios:70ce588b3f1298a1336b2b',
    messagingSenderId: '302397930802',
    projectId: 'flutter-lovers-323ec',
    storageBucket: 'flutter-lovers-323ec.appspot.com',
    iosClientId: '302397930802-l4vr062indvb6la02vk5s1m8gt1h0cca.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCanliSohbetUygulamasi',
  );
}
